[build]
  base = "./"
  publish = "./dist/"
  command = "npm run build"

[template.environment]
  NAME="Vinh Vo"
  PIC="https://github.com/AnshumanMahato/Happy-Birthday-Card/blob/e81a0d18709d00f45ed841c9d4a866389eca74dc/local/sample-pic.jpeg"